# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py{311,312,313,314}-{linux,macos,windows}
isolated_build=true

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
    
[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

[testenv]
constrain_package_deps = true
platform = 
    macos: darwin
    linux: linux
    windows: win32
passenv = 
    CI
    GITHUB_ACTIONS
    DISPLAY
    XAUTHORITY
    NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
    PYVISTA_OFF_SCREEN
deps = 
    pytest  # https://docs.pytest.org/en/latest/contents.html
    pytest-cov  # https://pytest-cov.readthedocs.io/en/latest/
    # you can remove these if you don't use them
    napari
    magicgui
    pytest-qt
    qtpy
    pyqt5
    pytest-xdist
    torch<2.9; sys_platform == "win32" and python_version < "3.14" # avoid missing dll issue on windows (no torch<2.9 wheels for 3.14)
    
commands = 
    python -c "import sys; print(sys.platform)"
    python -m pip show torch
    pytest {posargs} -v -n0 --color=yes --cov=napari_convpaint --cov-report=xml
